---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root  
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
  environment:
    NODE_ENV: "{{ lookup('env','NODE_ENV') }}"
    VERSION: "{{ lookup('env','VERSION') }}"
    ENVIRONMENT: "{{ lookup('env','ENVIRONMENT') }}" 
    TYPEORM_CONNECTION: "{{ lookup('env','TYPEORM_CONNECTION') }}"
    TYPEORM_HOST: "{{ lookup('env','TYPEORM_HOST') }}"
    TYPEORM_USERNAME: "{{ lookup('env','TYPEORM_USERNAME') }}"
    TYPEORM_PASSWORD: "{{ lookup('env','TYPEORM_PASSWORD') }}"
    TYPEORM_DATABASE: "{{ lookup('env','TYPEORM_DATABASE') }}"
    TYPEORM_PORT: "{{ lookup('env','TYPEORM_PORT') }}"
    TYPEORM_ENTITIES: "{{ lookup('env','TYPEORM_ENTITIES') }}"
    TYPEORM_MIGRATIONS: "{{ lookup('env', 'TYPEORM_MIGRATIONS')}}"
    TYPEORM_MIGRATIONS_DIR: "{{ lookup('env', 'TYPEORM_MIGRATIONS_DIR')}}"
  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      # Your code here
      wait_for_connection:
        delay: 60
        timeout: 600
    - name: "install python for Ansible."
      become: yes
      apt:
        name: "python3-pip"
        update_cache: yes
        state: present
    - name: 'Wait port 22 to become reachable/usable.'
      wait_for:
        port: 22
        delay: 10

  roles:
    - configure-server
    - configure-prometheus-node-exporter